<table width=60%>
    <tr style="background-color: white;">
        <td><img src='https://www.creativedestructionlab.com/wp-content/uploads/2018/05/xanadu.jpg'></td>></td>
    </tr>
</table>

---

<img src='https://raw.githubusercontent.com/XanaduAI/strawberryfields/master/doc/_static/strawberry-fields-text.png'>

---

<br>

<center> <h1> Gaussian boson sampling tutorial </h1></center>

To get a feel for how Strawberry Fields works, let's try coding a quantum program, Gaussian boson sampling.

## Background information: Gaussian states

A Gaussian state is one that can be described by a [Gaussian function](https://en.wikipedia.org/wiki/Gaussian_function) in the phase space. For example, for a single mode Gaussian state, squeezed in the $x$ quadrature by squeezing operator $S(r)$, could be described by the following [Wigner quasiprobability distribution](Wigner quasiprobability distribution):

$$W(x,p) = \frac{2}{\pi}e^{-2\sigma^2(x-\bar{x})^2 - 2(p-\bar{p})^2/\sigma^2}$$

where $\sigma$ represents the **squeezing**, and $\bar{x}$ and $\bar{p}$ are the mean **displacement**, respectively. For multimode states containing $N$ modes, this can be generalised; Gaussian states are uniquely defined by a [multivariate Gaussian function](https://en.wikipedia.org/wiki/Multivariate_normal_distribution), defined in terms of the **vector of means** ${\mu}$ and a **covariance matrix** $\sigma$.

### The position and momentum basis

For example, consider a single mode in the position and momentum quadrature basis (the default for Strawberry Fields). Assuming a Gaussian state with displacement $\alpha = \bar{x}+i\bar{p}$ and squeezing $\xi = r e^{i\phi}$ in the phase space, it has a vector of means and a covariance matrix given by:

$$ \mu = (\bar{x},\bar{p}),~~~~~~\sigma = SS\dagger=R(\phi/2)\begin{bmatrix}e^{-2r} & 0 \\0 & e^{2r} \\\end{bmatrix}R(\phi/2)^T$$

where $S$ is the squeezing operator, and $R(\phi)$ is the standard two-dimensional rotation matrix. For multiple modes, in Strawberry Fields we use the convention 

$$ \mu = (\bar{x}_1,\bar{x}_2,\dots,\bar{x}_N,\bar{p}_1,\bar{p}_2,\dots,\bar{p}_N)$$

and therefore, considering $\phi=0$ for convenience, the multimode covariance matrix is simply

$$\sigma = \text{diag}(e^{-2r_1},\dots,e^{-2r_N},e^{2r_1},\dots,e^{2r_N})\in\mathbb{C}^{2N\times 2N}$$

If a continuous-variable state *cannot* be represented in the above form (for example, a single photon Fock state or a cat state), then it is non-Gaussian.

### The annihilation and creation operator basis

If we are instead working in the creation and annihilation operator basis, we can use the transformation of the single mode squeezing operator

$$ S(\xi) \left[\begin{matrix}\hat{a}\\\hat{a}^\dagger\end{matrix}\right] = \left[\begin{matrix}\cosh(r)&-e^{i\phi}\sinh(r)\\-e^{-i\phi}\sinh(r)&\cosh(r)\end{matrix}\right] \left[\begin{matrix}\hat{a}\\\hat{a}^\dagger\end{matrix}\right]$$

resulting in

$$\sigma = SS^\dagger = \left[\begin{matrix}\cosh(2r)&-e^{i\phi}\sinh(2r)\\-e^{-i\phi}\sinh(2r)&\cosh(2r)\end{matrix}\right]$$

For multiple Gaussian states with non-zero squeezing, the covariance matrix in this basis simply generalises to

$$\sigma = \text{diag}(S_1S_1^\dagger,\dots,S_NS_N^\dagger)\in\mathbb{C}^{2N\times 2N}$$

## Introduction to Gaussian boson sampling

<div class="alert alert-info">
“If you need to wait exponential time for your single photon sources to emit simultaneously, then there would seem to be no advantage over classical computation. This is the reason why so far, boson sampling has only been demonstrated with 3-4 photons. When faced with these problems, until recently, all we could do was shrug our shoulders.” - [Scott Aaronson](https://www.scottaaronson.com/blog/?p=1579)
</div>

While [boson sampling](https://en.wikipedia.org/wiki/Boson_sampling) allows the experimental implementation of a quantum sampling problem that it countably hard classically, one of the main issues it has in experimental setups is one of **scalability**, due to its dependence on an array of simultaneously emitting single photon sources.

Currently, most physical implementations of boson sampling make use of a process known as [Spontaneous Parametric Down-Conversion](http://en.wikipedia.org/wiki/Spontaneous_parametric_down-conversion) to generate the single photon source inputs. Unfortunately, this method is non-deterministic - as the number of modes in the apparatus increases, the average time required until every photon source emits a simultaneous photon increases *exponentially*.

In order to simulate a *deterministic* single photon source array, several variations on boson sampling have been proposed; the most well known being scattershot boson sampling ([Lund, 2014](https://link.aps.org/doi/10.1103/PhysRevLett.113.100502)). However, a recent boson sampling variation by [Hamilton et al.](https://link.aps.org/doi/10.1103/PhysRevLett.119.170501) negates the need for single photon Fock states altogether, by showing that **incident Gaussian states** - in this case, single mode squeezed states - can produce problems in the same computational complexity class as boson sampling. Even more significantly, this negates the scalability problem with single photon sources, as single mode squeezed states can be easily simultaneously generated experimentally.

Aside from changing the input states from single photon Fock states to Gaussian states, the Gaussian boson sampling scheme appears quite similar to that of boson sampling:

1. $N$ single mode squeezed states $\left|{\xi_i}\right\rangle$, with squeezing parameters $\xi_i=r_ie^{i\phi_i}$, enter an $N$ mode linear interferometer with unitary $U$.
   <br>
  
2. The output of the interferometer is denoted $\left|{\psi'}\right\rangle$. Each output mode is then measured in the Fock basis, $\bigotimes_i n_i\left|{n_i}\middle\rangle\middle\langle{n_i}\right|$.

Without loss of generality, we can absorb the squeezing parameter $\phi$ into the interferometer, and set $\phi=0$ for convenience. The covariance matrix **in the creation and annihilation operator basis** at the output of the interferometer is then given by:

$$\sigma_{out} = \frac{1}{2} \left[ \begin{matrix}U&0\\0&U^*\end{matrix} \right]\sigma_{in} \left[ \begin{matrix}U^\dagger&0\\0&U^T\end{matrix} \right]$$

Using phase space methods, [Hamilton et al.](https://link.aps.org/doi/10.1103/PhysRevLett.119.170501) showed that the probability of measuring a Fock state is given by

$$\left|\left\langle{n_1,n_2,\dots,n_N}\middle|{\psi'}\right\rangle\right|^2 = \frac{\left|\text{Haf}[(U\bigoplus_i\tanh(r_i)U^T)]_{st}\right|^2}{n_1!n_2!\cdots n_N!\sqrt{|\sigma_{out}+I/2|}},$$

i.e. the sampled single photon probability distribution is proportional to the **Hafnian** of a submatrix of $U\bigoplus_i\tanh(r_i)U^T$, dependent upon the output covariance matrix.

<div class="alert alert-success" style="border: 0px; border-left: 3px solid #119a68; color: black; background-color: #daf0e9">

<p style="color: #119a68;">**The Hafnian**</p>

The Hafnian of a matrix is defined by
<br><br>
$$\text{Haf}(A) = \frac{1}{n!2^n}\sum_{\sigma=S_{2N}}\prod_{i=1}^N A_{\sigma(2i-1)\sigma(2i)}$$
<br>

$S_{2N}$ is the set of all permutations of $2N$ elements. In graph theory, the Hafnian calculates the number of perfect <a href="https://en.wikipedia.org/wiki/Matching_(graph_theory)">matchings</a> in an **arbitrary graph** with adjacency matrix $A$.
<br>

Compare this to the permanent, which calculates the number of perfect matchings on a *bipartite* graph - the Hafnian turns out to be a generalisation of the permanent, with the relationship

$$\begin{align}
\text{Per(A)} = \text{Haf}\left(\left[\begin{matrix}
0&A\\
A^T&0
\end{matrix}\right]\right)
\end{align}$$

As any algorithm that could calculate (or even approximate) the Hafnian could also calculate the permanent - a #P problem - it follows that calculating or approximating the Hafnian must also be a classically hard problem.
</div>

### Equally squeezed input states

In the case where all the input states are squeezed equally with squeezing factor $\xi=r$ (i.e. so $\phi=0$), we can simplify the denominator into a much nicer form. It can be easily seen that, due to the unitarity of $U$,

$$\left[ \begin{matrix}U&0\\0&U^*\end{matrix} \right] \left[ \begin{matrix}U^\dagger&0\\0&U^T\end{matrix} \right] = \left[ \begin{matrix}UU^\dagger&0\\0&U^*U^T\end{matrix} \right] =I$$

Thus, we have 

$$\begin{align}
\sigma_{out} +\frac{1}{2}I &= \sigma_{out} + \frac{1}{2} \left[ \begin{matrix}U&0\\0&U^*\end{matrix} \right] \left[ \begin{matrix}U^\dagger&0\\0&U^T\end{matrix} \right] = \left[ \begin{matrix}U&0\\0&U^*\end{matrix} \right] \frac{1}{2} \left(\sigma_{in}+I\right) \left[ \begin{matrix}U^\dagger&0\\0&U^T\end{matrix} \right]
\end{align}$$

where we have subtituted in the expression for $\sigma_{out}$. Taking the determinants of both sides, the two block diagonal matrices containing $U$ are unitary, and thus have determinant 1, resulting in

$$\left|\sigma_{out} +\frac{1}{2}I\right| =\left|\frac{1}{2}\left(\sigma_{in}+I\right)\right|=\left|\frac{1}{2}\left(SS^\dagger+I\right)\right| $$

By expanding out the right hand side, and using various trig identities, it is easy to see that this simply reduces to $\cosh^{2N}(r)$ where $N$ is the number of modes; thus the Gaussian boson sampling problem in the case of equally squeezed input modes reduces to

$$\left|\left\langle{n_1,n_2,\dots,n_N}\middle|{\psi'}\right\rangle\right|^2 = \frac{\left|\text{Haf}[(UU^T\tanh(r))]_{st}\right|^2}{n_1!n_2!\cdots n_N!\cosh^N(r)},$$

## The Gaussian boson sampling circuit
The multimode linear interferometer can be decomposed into two-mode beamsplitters (`BSgate`) and single-mode phase shifters (`Rgate`) (<a href="https://doi.org/10.1103/physrevlett.73.58">Reck, 1994</a>), allowing for an almost trivial translation into a continuous-variable quantum circuit.

For example, in the case of a 4 mode interferometer, with arbitrary $4\times 4$ unitary $U$, the continuous-variable quantum circuit for Gaussian boson sampling is given by

<img src="https://s3.amazonaws.com/xanadu-img/gaussian_boson_sampling.svg" width=70%/>

In the above,

* the single mode squeeze states all apply identical squeezing $\xi=r$,
* the detectors perform Fock state measurements (i.e. measuring the photon number of each mode),
* the parameters of the beamsplitters and the rotation gates determines the unitary $U$.

For $N$ input modes, we must have a minimum of $N$ columns in the beamsplitter array ([Clements, 2016](https://arxiv.org/abs/1603.08788)).

## Simulating boson sampling in Strawberry Fields



In [1]:
import strawberryfields as sf
from strawberryfields.ops import *
from strawberryfields.utils import random_interferometer

C:\Users\cgres\Anaconda3\envs\sf_tensorflow_env2\lib\site-packages\tensorflow\python\framework\dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\cgres\Anaconda3\envs\sf_tensorflow_env2\lib\site-packages\tensorflow\python\framework\dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\cgres\Anaconda3\envs\sf_tensorflow_env2\lib\site-packages\tensorflow\python\framework\dtypes.py:460: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\cgres\Anaconda3\envs\sf_t

Strawberry Fields makes this easy; there is an `Interferometer` quantum operation, and a utility function that allows us to generate the matrix representing a random interferometer.

In [2]:
U = random_interferometer(4)

The lack of Fock states and non-linear operations means we can use the Gaussian backend to simulate Gaussian boson sampling. In this example program, we are using input states with squeezing parameter $\xi=1$, and the randomly chosen interferometer generated above.

In [3]:
eng = sf.Engine('gaussian')
gbs = sf.Program(4)

with gbs.context as q:
    # prepare the input squeezed states
    S = Sgate(1)
    All(S) | q

    # interferometer
    Interferometer(U) | q
    MeasureFock() | q
    
results = eng.run(gbs, run_options={"shots":10})
state = results.state

# Note: Running this cell will generate a warning. This is just the Gaussian backend of Strawberryfields telling us 
# that, although it can carry out the MeasureFock operation, it will not update the state of the circuit after doing so,
# since the resulting state would be non-Gaussian. For this notebook, the warning can be safely ignored.

C:\Users\cgres\Anaconda3\envs\sf_tensorflow_env2\lib\site-packages\strawberryfields\backends\gaussianbackend\backend.py:200: UserWarning: Cannot simulate non-Gaussian states. Conditional state after Fock measurement has not been updated.


We can see the decomposed beamsplitters and rotation gates, by calling `eng.print_applied()`:

In [4]:
eng.print_applied()

Run 0:
Sgate(1, 0) | (q[0])
Sgate(1, 0) | (q[1])
Sgate(1, 0) | (q[2])
Sgate(1, 0) | (q[3])
Rgate(-1.106) | (q[0])
BSgate(0.6758, 0) | (q[0], q[1])
Rgate(-2.335) | (q[2])
BSgate(0.6619, 0) | (q[2], q[3])
Rgate(0.3969) | (q[1])
BSgate(1.203, 0) | (q[1], q[2])
Rgate(-0.2382) | (q[0])
BSgate(1.331, 0) | (q[0], q[1])
Rgate(-1.28) | (q[0])
Rgate(2.912) | (q[1])
Rgate(0.01374) | (q[2])
Rgate(1.388) | (q[3])
BSgate(-0.7982, 0) | (q[2], q[3])
Rgate(-1.893) | (q[2])
BSgate(-0.3828, 0) | (q[1], q[2])
Rgate(-2.615) | (q[1])
Measure | (q[0], q[1], q[2], q[3])


<div class="alert alert-success" style="border: 0px; border-left: 3px solid #119a68; color: black; background-color: #daf0e9">
<p style="color: #119a68;">**Available decompositions**</p>

Check out our <a href="https://strawberryfields.readthedocs.io/en/stable/conventions/decompositions.html">documentation</a> to see the available CV decompositions available in Strawberry Fields.
</div>


We can also see some of the measurement samples from this circuit within `results.samples`. These correspond to independent runs of the Gaussian Boson Sampling circuit. 

In [6]:
results.samples

array([[2, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 2, 0, 2],
       [3, 2, 2, 3],
       [2, 0, 2, 2],
       [1, 1, 1, 1],
       [2, 0, 3, 1],
       [1, 0, 1, 0],
       [1, 3, 4, 0],
       [1, 0, 2, 1]])

## Analysis

Let's now verify the Gaussian boson sampling result, by comparing the output Fock state probabilities to the Hafnian, using the relationship

$$\left|\left\langle{n_1,n_2,\dots,n_N}\middle|{\psi'}\right\rangle\right|^2 = \frac{\left|\text{Haf}[(UU^T\tanh(r))]_{st}\right|^2}{n_1!n_2!\cdots n_N!\cosh^N(r)}$$

### Calculating the Hafnian

For the right hand side numerator, we first calculate the submatrix $[(UU^T\tanh(r))]_{st}$:

In [7]:
import numpy as np
B = (np.dot(U, U.T) * np.tanh(1))

In Gaussian boson sampling, we determine the submatrix by taking the rows and columns corresponding to the measured Fock state. For example, to calculate the submatrix in the case of the output measurement $\left|{1,1,0,0}\right\rangle$,

In [8]:
B[:,[0,1]][[0,1]]

array([[-0.04820543-0.55643423j, -0.10053267-0.20478706j],
       [-0.10053267-0.20478706j,  0.26978353-0.41793844j]])

To calculate the Hafnian in Python, we can use the direct definition

$$\text{Haf}(A) = \frac{1}{n!2^n} \sum_{\sigma \in S_{2n}} \prod_{j=1}^n A_{\sigma(2j - 1), \sigma(2j)}$$

Notice that this function counts each term in the definition multiple times, and renormalizes to remove the multiple counts by dividing by a factor $\frac{1}{n!2^n}$. **This function is extremely slow!**

In [9]:
from itertools import permutations
from scipy.special import factorial

def Haf(M):
    n = len(M)
    m = int(n/2)
    haf = 0.0
    for i in permutations(range(n)):
        prod = 1.0
        for j in range(m):
            prod *= M[i[2 * j], i[2 * j + 1]]
        haf += prod
    return haf / (factorial(m) * (2 ** m))

## Comparing to the SF result

In Strawberry Fields, both Fock and Gaussian states have the method `fock_prob()`, which returns the probability of measuring that particular Fock state.

#### Let's compare the case of measuring at the output state $\left|0,1,0,1\right\rangle$:

In [10]:
B = (np.dot(U, U.T) * np.tanh(1))[:, [1, 3]][[1, 3]]
np.abs(Haf(B)) ** 2 / np.cosh(1) ** 4

0.031609415387984494

In [11]:
state.fock_prob([0, 1, 0, 1])

0.0316094153879846

#### For the measurement result $\left|2,0,0,0\right\rangle$:

In [65]:
B = (np.dot(U, U.T) * np.tanh(1))[:, [0, 0]][[0, 0]]
np.abs(Haf(B)) ** 2 / (2 * np.cosh(1) ** 4)

0.02750999521119896

In [13]:
state.fock_prob([2, 0, 0, 0])

0.027509995211198953

#### For the measurement result $\left|1,1,0,0\right\rangle$:

In [14]:
B = (np.dot(U, U.T) * np.tanh(1))[:, [0, 1]][[0, 1]]
np.abs(Haf(B)) ** 2 / np.cosh(1) ** 4

0.009179538736835207

In [15]:
state.fock_prob([1, 1, 0, 0])

0.00917953873683522

#### For the measurement result $\left|1,1,1,1\right\rangle$, this corresponds to the full matrix $B$:

In [16]:
B = (np.dot(U,U.T) * np.tanh(1))
np.abs(Haf(B)) ** 2 / np.cosh(1) ** 4

0.011469919168501149

In [17]:
state.fock_prob([1, 1, 1, 1])

0.011469919168501192

#### For the measurement result $\left|0,0,0,0\right\rangle$, this corresponds to a **null** submatrix, which has a Hafnian of 1:

In [23]:
1 / np.cosh(1) ** 4


0.1763784476141347

In [24]:
state.fock_prob([0, 0, 0, 0])

0.17637844761413482

As you can see, like in the boson sampling tutorial, they agree with almost negligable difference.

<div class="alert alert-success" style="border: 0px; border-left: 3px solid #119a68; color: black; background-color: #daf0e9">
<p style="color: #119a68;">**Exercises**</p>

Repeat this notebook with 
<ol>
    <li> A higher value for <tt>shots</tt> in <tt>eng.run()</tt>, and compare the relative probabilties of events with the expected values.</li>
    <li> A Fock backend such as NumPy, instead of the Gaussian backend</li>
    <li> Different beamsplitter and rotation parameters</li>
    <li> Input states with *differing* squeezed values $r_i$. You will need to modify the code to take into account the fact that the output covariance matrix determinant must now be calculated!
</ol>
</div>

In [33]:
#1. Choose Shots to be 20 now

eng = sf.Engine('gaussian')
gbs = sf.Program(4)

with gbs.context as q:
    # prepare the input squeezed states
    S = Sgate(1)
    All(S) | q

    # interferometer
    Interferometer(U) | q
    MeasureFock() | q
    
results = eng.run(gbs, run_options={"shots":20})
state = results.state

#eng.print_applied()
#results.samples
B = (np.dot(U, U.T) * np.tanh(1))
B[:,[0,1]][[0,1]]


array([[-0.04820543-0.55643423j, -0.10053267-0.20478706j],
       [-0.10053267-0.20478706j,  0.26978353-0.41793844j]])

In [34]:
print(eng.print_applied(),'\n','\n','\n',results.samples)

Run 0:
Sgate(1, 0) | (q[0])
Sgate(1, 0) | (q[1])
Sgate(1, 0) | (q[2])
Sgate(1, 0) | (q[3])
Rgate(-1.106) | (q[0])
BSgate(0.6758, 0) | (q[0], q[1])
Rgate(-2.335) | (q[2])
BSgate(0.6619, 0) | (q[2], q[3])
Rgate(0.3969) | (q[1])
BSgate(1.203, 0) | (q[1], q[2])
Rgate(-0.2382) | (q[0])
BSgate(1.331, 0) | (q[0], q[1])
Rgate(-1.28) | (q[0])
Rgate(2.912) | (q[1])
Rgate(0.01374) | (q[2])
Rgate(1.388) | (q[3])
BSgate(-0.7982, 0) | (q[2], q[3])
Rgate(-1.893) | (q[2])
BSgate(-0.3828, 0) | (q[1], q[2])
Rgate(-2.615) | (q[1])
Measure | (q[0], q[1], q[2], q[3])
None 
 
 
 [[1 0 4 3]
 [0 0 0 0]
 [0 0 0 0]
 [3 4 3 0]
 [2 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 3 0 0]
 [1 0 1 0]
 [0 0 0 0]
 [2 0 0 0]
 [0 0 1 1]
 [0 0 0 0]
 [0 1 0 1]
 [0 0 0 0]
 [3 1 2 0]
 [3 0 1 0]
 [4 4 0 2]
 [2 3 1 2]]


In [35]:
print(state.fock_prob([0, 1, 0, 1]),'\n',state.fock_prob([2, 0, 0, 0]),'\n',
    state.fock_prob([1, 1, 0, 0]),'\n',state.fock_prob([1, 1, 1, 1]),'\n',
    state.fock_prob([0, 0, 0, 0]))

0.0316094153879846 
 0.027509995211198953 
 0.00917953873683522 
 0.011469919168501192 
 0.17637844761413482


In [51]:
# Increasing shots did not effect the probabilities, the results were the same.

In [ ]:
#2. Use a fock backend instead oF Gaussian

In [49]:
eng = sf.Engine('fock', backend_options={"cutoff_dim":10})
gbs = sf.Program(4)

with gbs.context as q:
    # prepare the input squeezed states
    S = Sgate(1)
    All(S) | q

    # interferometer
    Interferometer(U) | q
    MeasureFock() | q
    
results = eng.run(gbs)
state = results.state

#eng.print_applied()
#results.samples

B = (np.dot(U, U.T) * np.tanh(1))
B[:,[0,1]][[0,1]]




array([[-0.04820543-0.55643423j, -0.10053267-0.20478706j],
       [-0.10053267-0.20478706j,  0.26978353-0.41793844j]])

In [50]:
print(eng.print_applied(),'\n','\n','\n',results.samples)

Run 0:
Sgate(1, 0) | (q[0])
Sgate(1, 0) | (q[1])
Sgate(1, 0) | (q[2])
Sgate(1, 0) | (q[3])
Rgate(-1.106) | (q[0])
BSgate(0.6758, 0) | (q[0], q[1])
Rgate(-2.335) | (q[2])
BSgate(0.6619, 0) | (q[2], q[3])
Rgate(0.3969) | (q[1])
BSgate(1.203, 0) | (q[1], q[2])
Rgate(-0.2382) | (q[0])
BSgate(1.331, 0) | (q[0], q[1])
Rgate(-1.28) | (q[0])
Rgate(2.912) | (q[1])
Rgate(0.01374) | (q[2])
Rgate(1.388) | (q[3])
BSgate(-0.7982, 0) | (q[2], q[3])
Rgate(-1.893) | (q[2])
BSgate(-0.3828, 0) | (q[1], q[2])
Rgate(-2.615) | (q[1])
Measure | (q[0], q[1], q[2], q[3])
None 
 
 
 [0, 0, 0, 0]


In [51]:
print(state.fock_prob([0, 1, 0, 1]),'\n',state.fock_prob([2, 0, 0, 0]),'\n',
    state.fock_prob([1, 1, 0, 0]),'\n',state.fock_prob([1, 1, 1, 1]),'\n',
    state.fock_prob([0, 0, 0, 0]))

0.0 
 0.0 
 0.0 
 0.0 
 1.0


In [52]:
#3. Use different beam splitters and rotation parameters

In [67]:
U2 = random_interferometer(4)

eng = sf.Engine('gaussian')
gbs = sf.Program(4)

with gbs.context as q:
    # prepare the input squeezed states
    S = Sgate(1)
    All(S) | q

    # interferometer
    Interferometer(U2) | q
    MeasureFock() | q
    
results = eng.run(gbs, run_options={"shots":10})
state = results.state


#eng.print_applied()
#results.samples

B = (np.dot(U2, U2.T) * np.tanh(1))
B[:,[0,1]][[0,1]]



array([[ 0.51479529-0.22933374j, -0.27529063-0.09731268j],
       [-0.27529063-0.09731268j, -0.03895239-0.66858026j]])

In [68]:
print(eng.print_applied(),'\n','\n','\n',results.samples)

Run 0:
Sgate(1, 0) | (q[0])
Sgate(1, 0) | (q[1])
Sgate(1, 0) | (q[2])
Sgate(1, 0) | (q[3])
Rgate(-2.83) | (q[0])
BSgate(0.3916, 0) | (q[0], q[1])
Rgate(-0.3827) | (q[2])
BSgate(0.5602, 0) | (q[2], q[3])
Rgate(2.168) | (q[1])
BSgate(0.88, 0) | (q[1], q[2])
Rgate(-0.2634) | (q[0])
BSgate(1.176, 0) | (q[0], q[1])
Rgate(0.1752) | (q[0])
Rgate(1.328) | (q[1])
Rgate(3.096) | (q[2])
Rgate(0.5547) | (q[3])
BSgate(-1.051, 0) | (q[2], q[3])
Rgate(0.392) | (q[2])
BSgate(-0.1488, 0) | (q[1], q[2])
Rgate(1.095) | (q[1])
Measure | (q[0], q[1], q[2], q[3])
None 
 
 
 [[1 1 1 1]
 [0 0 0 0]
 [4 3 1 0]
 [0 0 4 2]
 [0 2 1 3]
 [0 0 0 0]
 [1 3 0 0]
 [0 1 1 2]
 [1 0 1 0]
 [4 0 2 4]]


In [69]:
print(state.fock_prob([0, 1, 0, 1]),'\n',state.fock_prob([2, 0, 0, 0]),'\n',
    state.fock_prob([1, 1, 0, 0]),'\n',state.fock_prob([1, 1, 1, 1]),'\n',
    state.fock_prob([0, 0, 0, 0]))

0.005028323175934745 
 0.028009616619309816 
 0.015037089804576633 
 0.0063006902096574766 
 0.1763784476141346


In [74]:
B = (np.dot(U2, U2.T) * np.tanh(1))[:, [1, 3]][[1, 3]]
np.abs(Haf(B)) ** 2 / np.cosh(1) ** 4

0.005028323175934762

In [75]:
B = (np.dot(U2, U2.T) * np.tanh(1))[:, [0, 0]][[0, 0]]
np.abs(Haf(B)) ** 2 / (2 * np.cosh(1) ** 4)

0.02800961661930988

In [76]:
B = (np.dot(U2, U2.T) * np.tanh(1))[:, [0, 1]][[0, 1]]
np.abs(Haf(B)) ** 2 / np.cosh(1) ** 4

0.015037089804576678

In [77]:
B = (np.dot(U2,U2.T) * np.tanh(1))
np.abs(Haf(B)) ** 2 / np.cosh(1) ** 4

0.006300690209657493

In [78]:
1 / np.cosh(1) ** 4

0.1763784476141347

In [62]:
# This changed the probabilities from the original case, as expected

In [63]:
#4. Use differeng squeezed values

In [123]:

eng = sf.Engine('gaussian')
gbs = sf.Program(4)

with gbs.context as q:
    # prepare the input squeezed states
    Sgate(1) | q[0]
    Sgate(2) | q[1]
    Sgate(3) | q[2]
    Sgate(4) | q[3]

    # interferometer
    Interferometer(U) | q
    MeasureFock() | q
    
results = eng.run(gbs, run_options={"shots":10})
state = results.state

print( "Squeesed values are now 1,2,3,4 for q[0]-q[3]")

#eng.print_applied()
#results.samples
B = (np.dot(U, U.T) * np.tanh(1))
B[:,[0,1]][[0,1]]


Squeesed values are now 1,2,3,4 for q[0]-q[3]


array([[-0.04820543-0.55643423j, -0.10053267-0.20478706j],
       [-0.10053267-0.20478706j,  0.26978353-0.41793844j]])

In [124]:
# Find the determinant dependent prefactor

import scipy as sp

UT = np.matrix.transpose(U)
Ustar = np.ndarray.conjugate(U)
Uherm = np.ndarray.conjugate(UT)


def S(r):
    a = np.cosh(r)
    b = -np.sinh(r)
    mat = np.array([[a, b],[b, a]])
    return mat

def Sherm(x):
    s = S(x)
    sT = np.matrix.transpose(s)
    sHerm = np.ndarray.conjugate(sT)
    return sHerm

    
c11 = np.dot(S(1),Sherm(1))
c22 = np.dot(S(2),Sherm(2))
c33 = np.dot(S(3),Sherm(3))
c44 = np.dot(S(4),Sherm(4))

cov_in = sp.linalg.block_diag(c11,c22,c33,c44)

cov_out_partial = .5 * np.dot(sp.linalg.block_diag(U,Ustar),cov_in)

cov_out = np.dot(cov_out_partial, sp.linalg.block_diag(Uherm,UT))

cov_det = sp.linalg.det(np.add(cov_out, .5*np.identity(8)))

det = (np.abs(cov_det))**.5
print(det)

1596.0710718165524


In [129]:
# Now simply replace the cosh^2N(r) and tanh(r) with det and tanh(ri)

print(state.fock_prob([0, 1, 0, 1]),'\n',state.fock_prob([2, 0, 0, 0]),'\n',
    state.fock_prob([1, 1, 0, 0]),'\n',state.fock_prob([1, 1, 1, 1]),'\n',
    state.fock_prob([0, 0, 0, 0]), '\n\n\n')


t = np.tanh(1)*U2.T + np.tanh(2)*U2.T + np.tanh(3)*U2.T + np.tanh(4)*U2.T


B = (np.dot(U2, t))[:, [1, 3]][[1, 3]]
print(np.abs(Haf(B)) ** 2 / det)

B = (np.dot(U2, t))[:, [0, 0]][[0, 0]]
print(np.abs(Haf(B)) ** 2 / (2 * det))

B = (np.dot(U2, t))[:, [0, 1]][[0, 1]]
print(np.abs(Haf(B)) ** 2 / det)

B = (np.dot(U2,t))
print(np.abs(Haf(B)) ** 2 / det)

print(1 / det)

0.000163290256289544 
 0.00016354240979142684 
 6.097186549168708e-05 
 0.00010524152862524394 
 0.0006265385155197168 



0.0004261529176992959
0.0023738290933813396
0.001274400922477586
0.012740029582915341
0.0006265385155197757


In [137]:
t = [np.tanh(1)*U2.T,np.tanh(2)*U2.T, np.tanh(3)*U2.T,np.tanh(4)*U2.T]

C = 0
for T in t:
    C = C + np.dot(U2,T) 

B = (C)[:, [1, 3]][[1, 3]]
print(np.abs(Haf(B)) ** 2 / det)

B = (C)[:, [0, 0]][[0, 0]]
print(np.abs(Haf(B)) ** 2 / (2 * det))

B = (np.dot(U2, t))[:, [0, 1]][[0, 1]]
print(np.abs(Haf(B)) ** 2 / det)

B = (np.dot(U2,t))
print(np.abs(Haf(B)) ** 2 / det)

print(1 / det)

0.0004261529176992959
0.0023738290933813396
[4.57165300e-05 1.21700906e-04 2.33486675e-05 4.56542637e-05]
[2.73400577e-05 2.60033626e-05 5.05453551e-06 3.84465306e-05]
0.0006265385155197757
